apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: livemech-mysql
spec:
  secretName: livemech-mysql-secret
  tlsUseSelfSigned: true
  instances: 1
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
