apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: livemech-mysql
spec:
  secretName: livemech-mysql-secret
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 2
  datadirVolumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi
