apiVersion: v1
kind: Secret
metadata:
  name: livemech-mysql-secret
stringData:
  rootUser: root
  rootHost: "%"
  rootPassword: "Password47"
---
apiVersion: v1
kind: Secret
metadata:
  name: livemech-secret
type: Opaque
stringData:
  DATABASE_URL: "mysql+asyncmy://root:Password47@livemech-mysql:3306/livemech"
