apiVersion: apps/v1
kind: Deployment
metadata:
  name: livemech
spec:
  replicas: 6
  selector:
    matchLabels:
      app: livemech
  template:
    metadata:
      labels:
        app: livemech
    spec:
      initContainers:
        - name: run-migrations
          image: koskedk/livemech:0.0.2
          command: ["/code/.venv/bin/alembic", "upgrade", "head"]
          workingDir: /code
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: livemech-secret
                  key: DATABASE_URL
      containers:
        - name: livemech
          image: koskedk/livemech:0.0.2
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: livemech-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
